Repository openchia/web, pull requests merged in 2022-03, with the labels that each got.

#231 Add space in the front of an info circle
  src/app/explorer/dashboard/dashboard.component.html
Labels: enhancement

#232 Use fixed values on axis charts (issue #229)
  src/app/stats/stats.component.ts
Labels: enhancement

#237 Improve/global
  .github/assets/landing.png
  README.md
  src/app/explorer/farmer/farmer.component.html
  src/app/explorer/farmer/farmer.component.ts
  src/app/join/join.component.html
  src/app/landing/landing.component.html
Labels: enhancement

#238 Improve login page
  src/app/explorer/login/login.component.css
  src/app/explorer/login/login.component.html
Labels: enhancement

#246 Fix launcher.share_pplns number for progress bar (issue #244)
  src/app/explorer/dashboard/dashboard.component.html
Labels: bug

#248 Improve navbar
  src/app/shared/navbar/navbar.component.html
  src/assets/scss/custom/_variables-common.scss
Labels: enhancement

#249 Add clipboard copy on join page
  src/app/join/join.component.html
  src/app/join/join.component.scss
  src/app/join/join.component.ts
Labels: enhancement

#250 Review and update partners page
  src/app/partners/partners.component.css
  src/app/partners/partners.component.html
  src/assets/img/partners/spacescan/spacescan-screenshot-1.png
  src/assets/img/partners/spacescan/spacescan-screenshot-2.png
  src/assets/img/partners/vivid-pool-logo.png
  src/assets/img/partners/vivid-stake-pool/vivid-stake-pool-screenshot-1.png
  src/assets/img/partners/vivid-stake-pool/vivid-stake-pool-screenshot-2.png
  src/assets/img/partners/vivid.png
Labels: enhancement

#251 Improvements/global
  src/app/explorer/farmer/farmer.component.html
  src/app/join/join.component.html
  src/app/partners/partners.component.css
  src/app/partners/partners.component.html
  src/assets/img/partners/spacescan/spacescan-screenshot-1.png
  src/assets/img/partners/spacescan/spacescan-screenshot-2.png
  src/assets/img/partners/vivid-stake-pool/vivid-stake-pool-screenshot-1.png
  src/assets/img/partners/vivid-stake-pool/vivid-stake-pool-screenshot-2.png
Labels: enhancement

#254 Fix accordion blocks space
  src/app/fees/fees.component.html
  src/app/join/join.component.html
  src/app/partners/partners.component.html
  src/app/stats/stats.component.html
Labels: enhancement

#264 Improve space chart colors
  src/app/stats/stats.component.ts
Labels: bug

#271 Update package-lock.json via npm audit fix
  package-lock.json
Labels: security

#270 Upgrade font-awesome and minor fixes
  src/app/shared/navbar/navbar.component.html
  src/index.html
Labels: enhancement

#272 Improve payout page when no transaction
  src/app/explorer/payout/payout.component.html
  src/assets/scss/custom/_badge.scss
Labels: enhancement

#276 Translations: Fix missing space between Estimated_Size and info-circle
  src/app/explorer/farmer/farmer.component.html
Labels: enhancement

#280 Add a warning icon in the navbar if duststorm is true
  src/app/shared/navbar/navbar.component.html
  src/app/shared/navbar/navbar.component.scss
  src/app/shared/navbar/navbar.component.ts
Labels: enhancement

#281 Add dust storm title and improve i18n
  src/app/shared/navbar/navbar.component.html
Labels: enhancement
